### ISSUE TITLE
Failed import of interface information to netbox

### ISSUE THREAD

**Issue by Wo0dsi3** [Anthony25/netbox-netprod-importer#2]
Hi there,

I have installed the netbox-netprod-importer
When I run it.. 
It logs onto the network device and pulls the interface information ok. 

It fails though when it tries to push this data to Netbox via HTTP.  (The same GET command runs ok from a separate windows server)

Performing system checks...

System check identified no issues (0 silenced).
January 14, 2019 - 14:38:14
Django version 2.0.9, using settings 'netbox.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[14/Jan/2019 14:38:20] "GET / HTTP/1.1" 200 77126
[14/Jan/2019 14:38:30] "GET /api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50 HTTP/1.1" 200 8349
[14/Jan/2019 14:38:30] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[14/Jan/2019 14:38:30] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
[14/Jan/2019 14:38:30] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[14/Jan/2019 14:38:30] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[14/Jan/2019 14:38:30] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
[14/Jan/2019 14:38:30] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[14/Jan/2019 14:38:30] "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
[14/Jan/2019 14:38:30] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[14/Jan/2019 14:38:30] "GET /favicon.ico HTTP/1.1" 404 29205
[14/Jan/2019 14:39:28] "GET /api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50 HTTP/1.1" 400 26
[14/Jan/2019 14:41:57] "GET /api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50 HTTP/1.1" 400 26

--------

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: show ipv6 interface
Glan-EU-GPN-WSE-MPLS#
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8000
DEBUG:urllib3.connectionpool:http://localhost:8000 "GET /api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50 HTTP/1.1" 400 None
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
Glan-EU-GPN-WSE-MPLS#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:exit_config_mode:
DEBUG:netmiko:write_channel: b'exit\n'
ERROR:netbox_importer:Error when polling device Glan-EU-GPN-WSE-MPLS: 400 Client Error: Bad Request for url: http://localhost:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50
100%|âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ| 1/1 [00:21<00:00, 21.86s/it]
btadmin@STLPBTDC0693:/etc/netbox_importer$

**Comment by Anthony25** [comment]
Hi,
Thanks a lot for the bug report.

As we discussed about it by email, I need more debug to understand the error, so I added more verbose exceptions in my code. Could you try using the `dev` branch (commit 82e81be) with the `--debug` option, and paste me the output like you did before, please?

**Comment by Wo0dsi3** [comment]
Sry for the delay..  Got stuck on something in work that took all my time.
How do I commit this  ? Not too sure on this process ?

**Comment by Anthony25** [comment]
Run my script from the `dev` branch and you should see more debug than before

**Comment by Wo0dsi3** [comment]
Didn't manage to get any extra info..
Possibility I am doing it incorrectly though..
Quick Webex ?


Glan-EU-GPN-WSE-MPLS#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show ipv6 interface\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: show ipv6 interface
Glan-EU-GPN-WSE-MPLS#
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8000
DEBUG:urllib3.connectionpool:http://localhost:8000 "GET /api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50 HTTP/1.1" 400 None
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
Glan-EU-GPN-WSE-MPLS#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:exit_config_mode:
DEBUG:netmiko:write_channel: b'exit\n'
ERROR:netbox_importer:Error when polling device Glan-EU-GPN-WSE-MPLS: 400 Client Error: Bad Request for url: http://localhost:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50
100%|ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ| 1/1 [00:13<00:00, 13.01s/it]
btadmin@STLPBTDC0693:/etc/netbox-netprod-importer$

**Comment by Anthony25** [comment]
Here is what you have to do:
```
git clone git@github.com:Anthony25/netbox-netprod-importer.git
cd netbox-netprod-importer
git checkout dev
sudo pip install -f .
```
And start `netbox-netprod-importer` like you did before.

**Comment by Wo0dsi3** [comment]
Thanks Anthony..

Small bit more info..

DEBUG:netmiko:read_channel:
Glan-EU-GPN-WSE-MPLS#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show ipv6 interface\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: show ipv6 interface
Glan-EU-GPN-WSE-MPLS#
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8000
DEBUG:urllib3.connectionpool:http://localhost:8000 "GET /api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50 HTTP/1.1" 400 None
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
Glan-EU-GPN-WSE-MPLS#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:exit_config_mode:
DEBUG:netmiko:write_channel: b'exit\n'
ERROR:netbox_importer:Error when polling device Glan-EU-GPN-WSE-MPLS: 400 Client Error: Bad Request for url: http://localhost:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50 -- <h1>Bad Request (400)</h1>
100%|âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ| 1/1 [00:12<00:00, 12.71s/it]

**Comment by Anthony25** [comment]
Try to just do a `curl http://localhost:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50` and print the response here. Apparently there isn't even a netbox error in the answer.

**Comment by Wo0dsi3** [comment]
Sure.. Here we go..

btadmin@STLPBTDC0693:/etc/netbox-netprod-importer$ curl http://localhost:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50
[3] 20533
btadmin@STLPBTDC0693:/etc/netbox-netprod-importer$ <h1>Bad Request (400)</h1>
[3]+  Done                    curl http://localhost:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS

Ont time when I used the IP address of the server instead of local host below is returned


btadmin@STLPBTDC0693:/etc/netbox-netprod-importer$ curl http://10.2.253.25:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS&limit=50
[3] 20539
btadmin@STLPBTDC0693:/etc/netbox-netprod-importer$ <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Error Message</TITLE>
<META http-equiv=Content-Type content="text/html; charset=UTF-8">
<STYLE id=L_10060_1>A {
      FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma
}
A:hover {
      FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma
}
TD {
      FONT-SIZE: 8pt; FONT-FAMILY: tahoma
}
TD.titleBorder {
      BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
}
TD.titleBorderx {
      BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
}
.TitleDescription {
      FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma
}
SPAN.explain {
      FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
}
SPAN.TryThings {
      FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
}
.TryList {
      MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma
}
.X {
      BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4
}
.adminList {
      MARGIN-TOP: 2px
}
</STYLE>
<META content="MSHTML 6.00.2800.1170" name=GENERATOR></HEAD>
<BODY bgColor=#f3f3ed>
<TABLE cellSpacing=0 cellPadding=0 width="100%">
  <TBODY>
  <TR>
    <TD class=titleBorderx width=30>
      <TABLE height=25 cellSpacing=2 cellPadding=0 width=25 bgColor=black>
        <TBODY>
        <TR>
          <TD id=L_10060_x class=x valign=middle align=center>X</TD>
        </TR>
        </TBODY>
      </TABLE>
    </TD>
    <TD class=titleBorder id=L_10060_2>Network Access Message:<SPAN class=TitleDescription> The page cannot be displayed</SPAN> </TD>
  </TR>
  </TBODY>
</TABLE>

<TABLE id=spacer>
  <TBODY>
  <TR>
    <TD height=10></TD></TR></TBODY></TABLE>
<TABLE width=400>
  <TBODY>
  <TR>
    <TD noWrap width=25></TD>
    <TD width=400><SPAN class=explain><ID id=L_10060_3><B>Explanation:</B></ID></SPAN><ID id=L_10060_4> The request timed out before the page could be retrieved. </ID><BR><BR>
    <B><SPAN class=tryThings><ID id=L_10060_5><B>Try the following:</B></ID></SPAN></B>
      <UL class=TryList>
        <LI id=L_10060_6><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
<LI id=L_10060_7><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
<LI id=L_10060_8><B>Contact website:</B> You may want to contact the website administrator to make sure the Web page still exists. You can do this by using the e-mail address or phone number listed on the website home page.

      </UL>
<ID id=L_10060_9>If you are still not able to view the requested page, try contacting your administrator or Helpdesk.</ID> <BR><BR>
    </TD>
  </TR>
  </TBODY>
</TABLE>

<TABLE id=spacer><TBODY><TR><TD height=15></TD></TR></TBODY></TABLE>

<TABLE width=400>
  <TBODY>
  <TR>
    <TD noWrap width=25></TD>
    <TD width=400 id=L_10060_10><B>Technical Information (for support personnel)</B>
      <UL class=adminList>
        <LI id=L_10060_11>Error Code 10060: Connection timeout
<LI id=L_10060_12>Background: The gateway could not receive a timely response from the website you are trying to access. This might indicate that the network is congested, or that the website is experiencing technical difficulties.
<LI id=L_10060_13>Date: 22/01/2019 20:18:25 [GMT]
<LI id=L_10060_14>Server: STLPBTDC0531
<LI id=L_10060_15>Source: Firewall

      </UL>
    </TD>
  </TR>
  </TBODY>
</TABLE>

</BODY>
</HTML>

 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Error Message</TITLE>
<META http-equiv=Content-Type content="text/html; charset=UTF-8">
<STYLE id=L_10060_1>A {
      FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma
}
A:hover {
      FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma
}
TD {
      FONT-SIZE: 8pt; FONT-FAMILY: tahoma
}
TD.titleBorder {
      BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
}
TD.titleBorderx {
      BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
}
.TitleDescription {
      FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma
}
SPAN.explain {
      FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
}
SPAN.TryThings {
      FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
}
.TryList {
      MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma
}
.X {
      BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4
}
.adminList {
      MARGIN-TOP: 2px
}
</STYLE>
<META content="MSHTML 6.00.2800.1170" name=GENERATOR></HEAD>
<BODY bgColor=#f3f3ed>
<TABLE cellSpacing=0 cellPadding=0 width="100%">
  <TBODY>
  <TR>
    <TD class=titleBorderx width=30>
      <TABLE height=25 cellSpacing=2 cellPadding=0 width=25 bgColor=black>
        <TBODY>
        <TR>
          <TD id=L_10060_x class=x valign=middle align=center>X</TD>
        </TR>
        </TBODY>
      </TABLE>
    </TD>
    <TD class=titleBorder id=L_10060_2>Network Access Message:<SPAN class=TitleDescription> The page cannot be displayed</SPAN> </TD>
  </TR>
  </TBODY>
</TABLE>

<TABLE id=spacer>
  <TBODY>
  <TR>
    <TD height=10></TD></TR></TBODY></TABLE>
<TABLE width=400>
  <TBODY>
  <TR>
    <TD noWrap width=25></TD>
    <TD width=400><SPAN class=explain><ID id=L_10060_3><B>Explanation:</B></ID></SPAN><ID id=L_10060_4> The request timed out before the page could be retrieved. </ID><BR><BR>
    <B><SPAN class=tryThings><ID id=L_10060_5><B>Try the following:</B></ID></SPAN></B>
      <UL class=TryList>
        <LI id=L_10060_6><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
<LI id=L_10060_7><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
<LI id=L_10060_8><B>Contact website:</B> You may want to contact the website administrator to make sure the Web page still exists. You can do this by using the e-mail address or phone number listed on the website home page.

      </UL>
<ID id=L_10060_9>If you are still not able to view the requested page, try contacting your administrator or Helpdesk.</ID> <BR><BR>
    </TD>
  </TR>
  </TBODY>
</TABLE>

<TABLE id=spacer><TBODY><TR><TD height=15></TD></TR></TBODY></TABLE>

<TABLE width=400>
  <TBODY>
  <TR>
    <TD noWrap width=25></TD>
    <TD width=400 id=L_10060_10><B>Technical Information (for support personnel)</B>
      <UL class=adminList>
        <LI id=L_10060_11>Error Code 10060: Connection timeout
<LI id=L_10060_12>Background: The gateway could not receive a timely response from the website you are trying to access. This might indicate that the network is congested, or that the website is experiencing technical difficulties.
<LI id=L_10060_13>Date: 22/01/2019 20:18:31 [GMT]
<LI id=L_10060_14>Server: STLPBTDC0531
<LI id=L_10060_15>Source: Firewall

      </UL>
    </TD>
  </TR>
  </TBODY>
</TABLE>

</BODY>
</HTML>

^C
[1]   Done                    curl http://10.2.253.25:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS
[2]-  Done                    curl http://10.2.253.25:8000/api/dcim/devices/?name=Glan-EU-GPN-WSE-MPLS

**Comment by Anthony25** [comment]
You seem to have an issue with the way Netbox is configured on your server. Fix your reverse proxy for `/api` and it should be good ;)

**Comment by Wo0dsi3** [comment]
Ok thanks a mill Anthony.. 
I have no local DNS server setup on this server.. 
Can I add a static dns entry into the /etc/hosts file ?
Sry, I'm a network guy trying to admin a Linux server.

**Comment by Wo0dsi3** [comment]
I think I see what you mean.. localhost was resolving to an IPv6 address...
I have amended that but still get the same error

**Comment by Anthony25** [comment]
You can check from the swagger doc `http://10.2.253.25:8000/api/docs/` if everything is working. Try to open an issue on Netbox or ask on the google group if needed: https://groups.google.com/forum/#!forum/netbox-discuss

**Comment by Anthony25** [comment]
I'll close this issue for now, as it doesn't seem related to the importer but to your API.

Ask me if you need to reopen it.
