### ISSUE TITLE
Update interconnections for netbox 2.5

### ISSUE THREAD

**Issue by Anthony25** [Anthony25/netbox-netprod-importer#8]
Netbox 2.5 introduces the notion of cables, but drop the old way to interconnect 2 interfaces.

It should be updated here, depending of the Netbox version.

**Comment by VictorPavlushin** [comment]
[Patch to upgrade to Netbox 2.5](https://github.com/Anthony25/netbox-netprod-importer/pull/9)

**Comment by Anthony25** [comment]
Fixed in #9
